// index.ts | Caramel - lipgloss port for Bun

export { Style, NewStyle } from "./style"
export type { Position as StylePosition, UnderlineStyle } from "./style"
export { type Color, NoColor, fg, bg, reset, bold, dim, italic, underline, blink, reverse, strikethrough } from "./color"
export type { CompleteColor, AdaptiveColor } from "./color"
export { borders, type BorderStyle, type BorderType } from "./border"
export { Position, Top, Bottom, Center, Left, Right, positionValue } from "./position"
export type { Position as PositionType } from "./position"
export { JoinHorizontal, JoinVertical } from "./join"
export { Wrap, Truncate, Ellipsize } from "./wrap"
export { Whitespace, WithWhitespaceStyle, WithWhitespaceChars, Place, PlaceHorizontal, PlaceVertical } from "./whitespace"
export type { WhitespaceOption } from "./whitespace"
export { Table } from "./table"
export { Width, Height, Size } from "./size"
