// index.ts | Caramel - lipgloss port for Bun

export { Style, NewStyle, NBSP, NoTabConversion } from "./style"
export type { TextAlign as StylePosition, UnderlineStyle } from "./style"
export { type Color, NoColor, Color as ColorFactory, LightDark, Complete, fg, bg, ulColor, reset, bold, dim, italic, underline, blink, reverse, strikethrough, colorToAnsi } from "./color"
export type { CompleteColor, AdaptiveColor, LightDarkFunc, CompleteFunc, ColorProfile } from "./color"
export { borders, getTopSize, getRightSize, getBottomSize, getLeftSize, type BorderStyle, type BorderType } from "./border"
export { Top, Bottom, Center, Left, Right, positionValue } from "./position"
export type { Position } from "./position"
export { JoinHorizontal, JoinVertical } from "./join"
export { Wrap, Truncate, Ellipsize } from "./wrap"
export { Whitespace, WithWhitespaceStyle, WithWhitespaceChars, Place, PlaceHorizontal, PlaceVertical } from "./whitespace"
export type { WhitespaceOption } from "./whitespace"
export { Table, CreateTable } from "./table"
export { Width, Height, Size } from "./size"
export { Canvas, ScreenBuffer } from "./canvas"
export type { Cell, Drawable, Screen } from "./canvas"
export { Layer, LayerHit, Compositor } from "./layer"
export type { Rectangle } from "./layer"
export { List, New, Alphabet, Arabic, Roman, Bullet, Asterisk, Dash } from "./list"
export type { Items, Enumerator, ListIndenter } from "./list"
export { Tree, Leaf, Root, NewStringData, DefaultEnumerator, RoundedEnumerator, DefaultIndenter } from "./tree"
export type { Node, Children, StyleFunc, TreeEnumerator, TreeIndenter } from "./tree"
export { Blend1D, Blend2D, Alpha, Complementary, Darken, Lighten, isDarkColor } from "./blending"
export { StyleRanges, NewRange, type Range } from "./ranges"
export { StyleRunes } from "./runes"
export { Writer, Writer_ } from "./writer"
export { BackgroundColor, HasDarkBackground } from "./query"
